# Generated by Django 3.2.6 on 2022-10-31 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_champion_scoreboard_season_tournament_tournamenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='team1goals',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='PlayerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season')),
                ('tmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournament')),
            ],
        ),
    ]
