# Generated by Django 3.2.6 on 2022-10-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221101_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='team2goals',
            field=models.IntegerField(default=0),
        ),
    ]
